// ⛔️ NOT IN USE — DO NOT EDIT THIS FILE
// The live onboarding uses GrooveHeroScrollView.swift (non-V2).
// This file is an unused variant. Agents: do not modify, do not wire features here.

// GrooveHeroScrollView.swift — v2
// PAGE 1 — Hero with 3-column parallax video wall + CTA
// v3: AVPlayer-based hero video wall with player pooling
// NOTE: Requires HeroVideoCell, AVPlayerPool, HeroVideoColumnView, HeroVideoWallView
//       to be added to Xcode target. See HERO_VIDEO_INTEGRATION.md for setup.

import SwiftUI

// ─── Data ────────────────────────────────────────────────────────────────────
// 12 verified R2 videos — 4 unique per column. URLs verified HTTP 200.

private let column1URLs: [String] = [
    // Column 1 — scrolls DOWN
    "https://videos.trygrooveai.com/presets/big-guy-V5-AI.mp4",
    "https://videos.trygrooveai.com/presets/c-walk-V5-AI.mp4",
    "https://videos.trygrooveai.com/presets/trag-V5-AI.mp4",
    "https://videos.trygrooveai.com/presets/baby-boombastic.mp4",
]

private let column2URLs: [String] = [
    // Column 2 — scrolls UP (parallax)
    "https://videos.trygrooveai.com/presets/milkshake-V5-AI.mp4",
    "https://videos.trygrooveai.com/presets/ophelia-ai.mp4",
    "https://videos.trygrooveai.com/presets/coco-channel-75fcae6c.mp4",
    "https://videos.trygrooveai.com/woman-coco-channel.mp4",
]

private let column3URLs: [String] = [
    // Column 3 — scrolls DOWN
    "https://videos.trygrooveai.com/woman-big-guy.mp4",
    "https://videos.trygrooveai.com/demos/golden-retriever-big-guy.mp4",
    "https://videos.trygrooveai.com/demos/golden-retriever-coco-channel.mp4",
    "https://videos.trygrooveai.com/demos/golden-retriever-c-walk.mp4",
]

// ─── View ─────────────────────────────────────────────────────────────────────

struct GrooveHeroScrollViewV2: View {
    let onNext: () -> Void

    var body: some View {
        ZStack {
            GrooveOnboardingTheme.background.ignoresSafeArea()

            VStack(spacing: 0) {
                // ── Wordmark ────────────────────────────────────────────────────
                Text("GrooveAI")
                    .font(.system(size: 16, weight: .semibold))
                    .foregroundColor(.white.opacity(0.70))
                    .padding(.top, 56)

                Spacer().frame(height: 20)

                // ── 3-column parallax video wall (AVPlayer pooling) ────────────
                ZStack {
                    HeroVideoWallView(
                        column1URLs: column1URLs,
                        column2URLs: column2URLs,
                        column3URLs: column3URLs
                    )

                    // Top gradient fade
                    VStack {
                        LinearGradient(
                            colors: [GrooveOnboardingTheme.background, GrooveOnboardingTheme.background.opacity(0)],
                            startPoint: .top,
                            endPoint: .bottom
                        )
                        .frame(height: 32)
                        Spacer()
                    }
                    .allowsHitTesting(false)

                    // Bottom gradient fade
                    VStack {
                        Spacer()
                        LinearGradient(
                            colors: [GrooveOnboardingTheme.background.opacity(0), GrooveOnboardingTheme.background],
                            startPoint: .top,
                            endPoint: .bottom
                        )
                        .frame(height: 80)
                    }
                    .allowsHitTesting(false)
                }
                .clipped()

                Spacer().frame(height: 32)

                // ── Headline + Subline ──────────────────────────────────────────
                VStack(spacing: 10) {
                    Text("Make Anyone Drop the Beat")
                        .font(.system(size: 36, weight: .heavy))
                        .tracking(-0.5)
                        .foregroundColor(.white)
                        .multilineTextAlignment(.center)
                        .lineSpacing(-4)

                    Text("Pick a photo. Tap a dance. Watch the magic.")
                        .font(.system(size: 17, weight: .regular))
                        .foregroundColor(GrooveOnboardingTheme.textSecondary)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: 280)
                }
                .padding(.horizontal, 24)

                Spacer().frame(height: 28)

                // ── CTA Button with glow shadow ─────────────────────────────────
                Button(action: {
                    UIImpactFeedbackGenerator(style: .medium).impactOccurred()
                    onNext()
                }) {
                    Text("Make yours →")
                        .font(.system(size: GrooveOnboardingTheme.ctaFontSize, weight: .semibold))
                        .foregroundColor(.white)
                        .frame(maxWidth: .infinity)
                        .frame(height: GrooveOnboardingTheme.ctaButtonHeight)
                        .background(GrooveOnboardingTheme.blueAccent)
                        .clipShape(Capsule())
                        .shadow(color: GrooveOnboardingTheme.ctaShadow, radius: 12, y: 4)
                }
                .buttonStyle(CTAPressStyle())
                .padding(.horizontal, GrooveOnboardingTheme.ctaHorizontalPadding)
                .padding(.bottom, GrooveOnboardingTheme.ctaBottomPadding)
            }
        }
    }
}
